import type { Metadata } from "next";
import Link from "next/link";
import { EditorialInfoPage } from "../components/EditorialInfoPage";

export const metadata: Metadata = {
  title: "About Symbiome",
  description: "Meet Symbiome, a human-made instrumental music catalogue and licensing service for creators and businesses, powered by Lofi Girl.",
};

export default function AboutPage() {
  return (
    <EditorialInfoPage
      eyebrow="About Symbiome"
      title={<>Music licensing built<br />around people.</>}
      lead="Symbiome brings a broad catalogue of high-quality instrumental music into one clear service for creators and businesses. Every track begins with an artist, and every licensing route starts with how the music will actually be used."
      actions={[
        { label: "Explore the music", href: "/catalog" },
        { label: "Discover Lofi Girl", href: "https://www.lofigirl.com/", external: true, secondary: true },
      ]}
      highlights={[
        { value: "10,000+", label: "instrumental and background tracks" },
        { value: "1,000+", label: "artists represented worldwide" },
        { value: "0", label: "AI-generated tracks accepted" },
      ]}
      sections={[
        {
          id: "what-we-build",
          eyebrow: "The service",
          title: "One catalogue, two clear ways to use it.",
          content: (
            <>
              <p>Symbiome is designed around two different needs. Creators can choose a straightforward plan for music used on their own channels. Businesses can request rights shaped around a campaign, film, game, brand project or original commission.</p>
              <div className="support-route-grid">
                <Link className="support-route-card" href="/creators"><small>For Creators</small><strong>Music for the channels you own.</strong><span>Explore the creator service →</span></Link>
                <Link className="support-route-card" href="/business"><small>For Businesses</small><strong>Music and rights shaped around a brief.</strong><span>Explore business licensing →</span></Link>
              </div>
            </>
          ),
        },
        {
          id: "human-made",
          eyebrow: "The catalogue",
          title: "Made by artists, not generated by prompts.",
          content: (
            <>
              <p>Human authorship is a basic catalogue rule, not a marketing filter added at the end. Symbiome does not accept generative AI music into the catalogue.</p>
              <ul className="support-list">
                <li><strong>Artists stay visible</strong><span>Tracks remain connected to the people who wrote and produced them.</span></li>
                <li><strong>Artists participate in licensing</strong><span>Licensing income is paid directly and fairly through the service.</span></li>
                <li><strong>The music is organised for real work</strong><span>Moods, styles, uses and playlists help people find music that supports a project without taking it over.</span></li>
              </ul>
            </>
          ),
        },
        {
          id: "powered-by-lofi-girl",
          eyebrow: "The connection",
          title: "Powered by Lofi Girl.",
          content: (
            <>
              <p>Symbiome is presented as an independent licensing product powered by Lofi Girl. It brings the catalogue, artists and long experience of instrumental listening into a service made for videos, streams and commercial projects.</p>
              <p>You can explore the wider music, livestreams and releases on the <a href="https://www.lofigirl.com/" target="_blank" rel="noreferrer">official Lofi Girl website</a>.</p>
            </>
          ),
        },
        {
          id: "where-we-are-going",
          eyebrow: "The roadmap",
          title: "A service that can grow with the work.",
          content: (
            <>
              <p>The first focus is music: making the catalogue useful, the licensing route understandable and the connection to artists clear.</p>
              <ul className="support-list">
                <li><strong>Creator subscriptions</strong><span>Simple coverage for eligible videos, livestreams, social content and podcasts published on your own channels.</span></li>
                <li><strong>Commercial licensing</strong><span>Existing tracks and original commissions scoped around the media, territory, duration and exclusivity a project requires.</span></li>
                <li><strong>Music for physical spaces</strong><span>A simple background music service for venues is planned and currently marked as coming soon.</span></li>
              </ul>
            </>
          ),
        },
      ]}
    />
  );
}
